<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter_workspace</name>
   <tag></tag>
   <elementGuidId>f4902196-0c3b-44b1-ad55-c5ee9daf2e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='workspace']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;workspace&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b18aa53b-e414-48dd-986b-c52383a790ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a51525c-62c2-4572-bd1f-c5b27d7dacd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workspace</value>
      <webElementGuid>c20d114f-d555-478c-b256-4acf9987fffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>03ef210b-0889-4789-adbe-d5d3b0618df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Workspace</value>
      <webElementGuid>316019ee-d890-4c26-bd71-f9d8fb1d9a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>716d886a-4b45-4844-863f-28b69f4b398d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;col flex-between-center h-100 c-login&quot;]/div[@class=&quot;page-block col p8 gap2&quot;]/div[2]/div[@class=&quot;input-wrapper f-align-center px3 bg-white&quot;]/input[1]</value>
      <webElementGuid>e2618436-2685-4c44-b257-75d6c2aba0b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='workspace']</value>
      <webElementGuid>e6aeafd7-c23a-4787-ad23-cb65c3cb156a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/input</value>
      <webElementGuid>9556de69-4166-4664-a7d7-df11b89af13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6bac44f8-bf24-489e-a12d-959809e4c9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'workspace' and @placeholder = 'Workspace']</value>
      <webElementGuid>0a3646ad-9afb-4df5-9c00-1a77f097a744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
