<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Кнопка Опубликовать</name>
   <tag></tag>
   <elementGuidId>c8a65c56-0514-43bb-8789-95a6791a3c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/div/div/div/div[5]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.post-creation.col.gap4.p4.mb6 > div:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b895a13a-c703-4e8f-99fb-9edacd037c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Опубликовать</value>
      <webElementGuid>49183dca-7ede-4a3f-98ff-4a42ef75f893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[@class=&quot;container d-flex gap2 mt6&quot;]/div[1]/div[@class=&quot;post-creation col gap4 p4 mb6&quot;]/div[5]</value>
      <webElementGuid>ec5c896a-dfb7-422f-854b-daeba553b8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/div/div/div[5]</value>
      <webElementGuid>d3e2ebe4-2dd2-484a-8132-bd46d490a073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Расширенный редактор'])[1]/following::div[2]</value>
      <webElementGuid>906a7aaa-24a9-4d10-b440-8b0934d8cd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Новость компании'])[1]/following::div[4]</value>
      <webElementGuid>1cd63cb5-c67b-4bc2-a0c0-04db453550b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Андрей Шехов'])[1]/preceding::div[6]</value>
      <webElementGuid>3f4f94e5-0d23-40da-8b92-61d5eda79ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div[5]</value>
      <webElementGuid>716286c3-e57c-4af5-9782-22f397f96d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Опубликовать' or . = 'Опубликовать')]</value>
      <webElementGuid>97e4cb2d-7988-4ec0-a6ac-aa2d772c3abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
